"""Added Roles

Revision ID: 2bc444e9850a
Revises: 4a2ec3dce53c
Create Date: 2025-07-08 18:21:24.688110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2bc444e9850a"
down_revision: Union[str, Sequence[str], None] = "4a2ec3dce53c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = sa.Enum("admin", "user", name="role")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column("roles", role_enum, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "roles")
    # ### end Alembic commands ###
    role_enum.drop(op.get_bind())
